server:
  port: 8080
  context-path: /
  tomcat:
    uri-encoding: utf-8
    max-http-post-size: 1000

logging:
  level: debug

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0


